[workspace]
resolver = "3"
members = [
    "crates/demon-bluff-deducer",
    "crates/demon-bluff-gameplay-engine",
    "crates/demon-bluff-logic-engine",
    "crates/training-data-generator",
]

[profile.release]
opt-level = 3
codegen-units = 1
lto = true
