[package]
name = "training-data-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bevy = "0.16.1"
image = "0.25.8"
owned-drop = "0.1.1"
serde = "1.0.226"
serde_json = "1.0.145"
thiserror = "2.0.16"
xcap = { version = "0.7.1", features = ["image"] }
